"""revise table Record

Revision ID: 3fbe6fdefd6
Revises: None
Create Date: 2018-08-04 21:24:19.793804

"""

# revision identifiers, used by Alembic.
revision = '3fbe6fdefd6'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lents')
    op.add_column('records', sa.Column('lend_pic', sa.String(), nullable=True))
    op.add_column('records', sa.Column('returned', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'returned')
    op.drop_column('records', 'lend_pic')
    op.create_table('lents',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('returned', sa.BOOLEAN(), nullable=True),
    sa.Column('pic', sa.VARCHAR(length=64), nullable=True),
    sa.Column('items', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['items'], ['items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
