"""modify Item.warn_stock

Revision ID: 6e010f9678
Revises: 3fbe6fdefd6
Create Date: 2018-08-08 20:03:11.132648

"""

# revision identifiers, used by Alembic.
revision = '6e010f9678'
down_revision = '3fbe6fdefd6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customers')
    op.alter_column('items', 'warn_stock',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('records', sa.Column('ap_pic', sa.String(), nullable=True))
    op.add_column('records', sa.Column('customer', sa.String(), nullable=True))
    op.add_column('records', sa.Column('pn', sa.String(length=64), nullable=True))
    op.add_column('records', sa.Column('size', sa.String(length=64), nullable=True))
    op.add_column('records', sa.Column('spec', sa.String(length=64), nullable=True))
    op.drop_column('records', 'user_id')
    op.drop_column('records', 'customer_id')
    op.drop_column('records', 'item_id')
    op.create_index('ix_records_pn', 'records', ['pn'], unique=False)
    op.create_index('ix_records_size', 'records', ['size'], unique=False)
    op.create_index('ix_records_spec', 'records', ['spec'], unique=False)
    op.drop_index('ix_records_time', 'records')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_records_time', 'records', ['time'], unique=False)
    op.drop_index('ix_records_spec', 'records')
    op.drop_index('ix_records_size', 'records')
    op.drop_index('ix_records_pn', 'records')
    op.add_column('records', sa.Column('item_id', sa.INTEGER(), nullable=True))
    op.add_column('records', sa.Column('customer_id', sa.INTEGER(), nullable=True))
    op.add_column('records', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.drop_column('records', 'spec')
    op.drop_column('records', 'size')
    op.drop_column('records', 'pn')
    op.drop_column('records', 'customer')
    op.drop_column('records', 'ap_pic')
    op.alter_column('items', 'warn_stock',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('customers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=64), nullable=True),
    sa.Column('short_name', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
